<CustButton@Button>
    font_size: 18
    background_normal: 'images/boton_normal.png'
    background_down: 'images/boton_presionado.png'

<CustLabel@Label>
    font_size: 18
    color: 0.5, 0, 0, 1

<CustGridLayout@GridLayout>
    cols: 1
    rows: 8
    spacing:10
    padding:10

<Logo@Label>
    canvas:
        Rectangle:
            source: 'images/logo_unla.png'
            pos: self.pos
            size: 100, 110

<CustTextInput@TextInput>
    multiline: False
    font_size: 15
