#: import BoxLayout kivy.uix.boxlayout.BoxLayout
#: import NoTransition kivy.uix.screenmanager.NoTransition
#: import GridLayout kivy.uix.gridlayout.GridLayout
#: include kv/login.kv
#: include kv/alumno.kv
#: include kv/docente.kv
#: include kv/admin.kv
#: include kv/registrarse.kv
#: include kv/customwidgets.kv
#: include kv/popups.kv

ScreenManagement:
    transition: NoTransition()
    LoginScreen:
    AlumnoScreen:
    DocenteScreen:
    AdminScreen:
    RegistrarseScreen:
